# Data Cleaning Challenge Solutions

This challenge involves exploration and cleaning of data, which contains some unwanted columns and some missing values.

#### The dataset:

The data for this challenge describes the useage and prices of oil accross different countries.

You will see a file called petrol_data.csv inside the Data folder. 

### a) Load in the oil data. Save it as a DataFrame under the name petrol_df.

- first, import the pandas library using:

import pandas as pd

- Then, the dataset can be accessed using file path 'Data/petrol_data.csv'

Your code in the cell(s) below:

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/petrol_data.csv')
df

,Unnamed: 0,Country,Daily Oil Consumption (Barrels),World Share,Yearly Gallons Per Capita,Price Per Gallon (USD),Price Per Liter (USD),Price Per Liter (PKR)
0,0,United States,19687287.0,20.30%,934.3,5.19,1.37,289.97
1,1,China,12791553.0,13.20%,138.7,5.42,1.43,302.87
2,2,India,4443000.0,4.60%,51.4,5.05,1.33,281.93
3,3,Japan,4012877.0,4.10%,481.5,4.69,1.24,262.05
4,4,Russia,3631287.0,3.70%,383.2,3.41,0.90,190.56
...,...,...,...,...,...,...,...,...
182,182,Malta,47000.0,0.05%,1652.2,5.28,1.40,295.04
183,183,Fiji,16000.0,0.02%,281.2,5.27,1.39,294.41
184,184,Tuvalu,NaN,NaN,NaN,NaN,NaN,NaN
185,185,Laos,18000.0,0.02%,40.3,7.23,1.91,403.75
186,186,France,1705568.0,1.80%,404.3,8.27,2.19,462.13

### b) Perform some data exploration on petrol_df.

Your exploration could answer the following questions:
- What do the first 5 rows of the petrol_df DataFrame look like?
- What are column names in petrol_df?
- What datatypes of each column in petrol_df?
- How many rows and columns does petrol_df have?

Your code in the cell(s) below:

In [3]:
df.head(5)

,Unnamed: 0,Country,Daily Oil Consumption (Barrels),World Share,Yearly Gallons Per Capita,Price Per Gallon (USD),Price Per Liter (USD),Price Per Liter (PKR)
0,0,United States,19687287.0,20.30%,934.3,5.19,1.37,289.97
1,1,China,12791553.0,13.20%,138.7,5.42,1.43,302.87
2,2,India,4443000.0,4.60%,51.4,5.05,1.33,281.93
3,3,Japan,4012877.0,4.10%,481.5,4.69,1.24,262.05
4,4,Russia,3631287.0,3.70%,383.2,3.41,0.90,190.56

In [4]:
df.columns

Index(['Unnamed: 0', 'Country', 'Daily Oil Consumption (Barrels)',
       'World Share', 'Yearly Gallons Per Capita', 'Price Per Gallon (USD)',
       'Price Per Liter (USD)', 'Price Per Liter (PKR)'],
      dtype='object')

In [5]:
df.dtypes

Unnamed: 0                           int64
Country                             object
Daily Oil Consumption (Barrels)    float64
World Share                         object
Yearly Gallons Per Capita          float64
Price Per Gallon (USD)             float64
Price Per Liter (USD)              float64
Price Per Liter (PKR)              float64
dtype: object

In [6]:
df.shape #there are 8 columns and 187 rows

(187, 8)

### c) There is a column, 'Unnamed: 0', which is is a useless duplicate of the index column. Remove this column using the pandas .drop() method.

tip1: try running a cell with the following code:

petrol_df.drop? 

This will bring up information about the parameters (settings) that go inside the round brackets, so that you can customise the drop() function.

tip2: .drop() can be used to remove rows OR columns, so you will need to specify whether to operate on rows or columns using one of the function parameters.

tip3: you will need to do something to ensure that the changes are saved to the DataFrame, not just viewed.

Your code in the cell(s) below:

In [7]:
df.drop?

Signature:
df.drop(
    labels=None,
    axis: 'Axis' = 0,
    index=None,
    columns=None,
    level: 'Level | None' = None,
    inplace: 'bool' = False,
    errors: 'str' = 'raise',
)
Docstring:
Drop specified labels from rows or columns.

Remove rows or columns by specifying label names and corresponding
axis, or by specifying directly index or column names. When using a
multi-index, labels on different levels can be removed by specifying
the level. See the `user guide <advanced.shown_levels>`
for more information about the now unused levels.

Parameters
----------
labels : single label or list-like
    Index or column labels to drop. A tuple will be used as a single
    label and not treated as a list-like.
axis : {0 or 'index', 1 or 'columns'}, default 0
    Whether to drop labels from the index (0 or 'index') or
    columns (1 or 'columns').
index : single label or list-like
    Alternative to specifying axis (``labels, axis=0``
    is equivalent to ``index=labels``).
columns : single label or list-like
    Alternative to specifying axis (``labels, axis=1``
    is equivalent to ``columns=labels``).
level : int or level name, optional
    For MultiIndex, level from which the labels will be removed.
inplace : bool, default False
    If False, return a copy. Otherwise, do operation
    inplace and return None.
errors : {'ignore', 'raise'}, default 'raise'
    If 'ignore', suppress error and only existing labels are
    dropped.

Returns
-------
DataFrame or None
    DataFrame without the removed index or column labels or
    None if ``inplace=True``.

Raises
------
KeyError
    If any of the labels is not found in the selected axis.

See Also
--------
DataFrame.loc : Label-location based indexer for selection by label.
DataFrame.dropna : Return DataFrame with labels on given axis omitted
    where (all or any) data are missing.
DataFrame.drop_duplicates : Return DataFrame with duplicate rows
    removed, optionally only considering certain columns.
Series.drop : Return Series with specified index labels removed.

Examples
--------
>>> df = pd.DataFrame(np.arange(12).reshape(3, 4),
...                   columns=['A', 'B', 'C', 'D'])
>>> df
   A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

Drop columns

>>> df.drop(['B', 'C'], axis=1)
   A   D
0  0   3
1  4   7
2  8  11

>>> df.drop(columns=['B', 'C'])
   A   D
0  0   3
1  4   7
2  8  11

Drop a row by index

>>> df.drop([0, 1])
   A  B   C   D
2  8  9  10  11

Drop columns and/or rows of MultiIndex DataFrame

>>> midx = pd.MultiIndex(levels=[['lama', 'cow', 'falcon'],
...                              ['speed', 'weight', 'length']],
...                      codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2],
...                             [0, 1, 2, 0, 1, 2, 0, 1, 2]])
>>> df = pd.DataFrame(index=midx, columns=['big', 'small'],
...                   data=[[45, 30], [200, 100], [1.5, 1], [30, 20],
...                         [250, 150], [1.5, 0.8], [320, 250],
...                         [1, 0.8], [0.3, 0.2]])
>>> df
                big     small
lama    speed   45.0    30.0
        weight  200.0   100.0
        length  1.5     1.0
cow     speed   30.0    20.0
        weight  250.0   150.0
        length  1.5     0.8
falcon  speed   320.0   250.0
        weight  1.0     0.8
        length  0.3     0.2

Drop a specific index combination from the MultiIndex
DataFrame, i.e., drop the combination ``'falcon'`` and
``'weight'``, which deletes only the corresponding row

>>> df.drop(index=('falcon', 'weight'))
                big     small
lama    speed   45.0    30.0
        weight  200.0   100.0
        length  1.5     1.0
cow     speed   30.0    20.0
        weight  250.0   150.0
        length  1.5     0.8
falcon  speed   320.0   250.0
        length  0.3     0.2

>>> df.drop(index='cow', columns='small')
                big
lama    speed   45.0
        weight  200.0
        length  1.5
falcon  speed   320.0
        weight  1.0
        length  0.3

>>> df.drop(index='length', level=1)
                big     small
lama    speed   45.0    30.0
        weight  200.0   100.0
cow     speed   30.0    20.0
        weight  250.0   150.0
falcon  speed   320.0   250.0
        weight  1.0     0.8
File:      c:\users\tamsin\anaconda3\lib\site-packages\pandas\core\frame.py
Type:      method

In [8]:
df.drop(columns='Unnamed: 0', inplace=True)

In [9]:
df

,Country,Daily Oil Consumption (Barrels),World Share,Yearly Gallons Per Capita,Price Per Gallon (USD),Price Per Liter (USD),Price Per Liter (PKR)
0,United States,19687287.0,20.30%,934.3,5.19,1.37,289.97
1,China,12791553.0,13.20%,138.7,5.42,1.43,302.87
2,India,4443000.0,4.60%,51.4,5.05,1.33,281.93
3,Japan,4012877.0,4.10%,481.5,4.69,1.24,262.05
4,Russia,3631287.0,3.70%,383.2,3.41,0.90,190.56
...,...,...,...,...,...,...,...
182,Malta,47000.0,0.05%,1652.2,5.28,1.40,295.04
183,Fiji,16000.0,0.02%,281.2,5.27,1.39,294.41
184,Tuvalu,NaN,NaN,NaN,NaN,NaN,NaN
185,Laos,18000.0,0.02%,40.3,7.23,1.91,403.75
186,France,1705568.0,1.80%,404.3,8.27,2.19,462.13

### d)  Deal with the NaN values in the data by removing rows that contain any NaN values. Save the result to a DataFrame called petrol_clean.

How many rows were removed?

Tip: there is a Pandas method which allows you to drop rows containing NaN values from the DataFrame.

Your code in the cell(s) below:

In [10]:
df.dropna(inplace=True)

In [11]:
df.shape #dropped two rows

(185, 7)

### e) Save your cleaned data to a new .csv file. Call it petrol_cleaned.csv.

Your code in the cell(s) below:

In [12]:
df.to_csv('../data/petrol_cleaned.csv') # this would put the file next to the original source file within the Data folder

### f) Other than dropping rows, how else can missing data be dealt with?

In no more than 100 words, offer thoughts about the following: 
- Other Pandas methods that deal with NaN values.
- Cases where one method of dealing with NaNs may be more suitable than another method.

Your written text in the cell(s) below.

You could use 
- fillna using bfill, ffill (can be used on categorical or numeric data)
- fillna with the mean or median value (can only be used on numeric data)
- fillna with a hard-coded value such as 0 (can be used on categorical or numeric data)
- interpolate (can only be used on numeric data)

dropna is a suitable method if we can accept the associated data loss. Methods for predicting and filling NaN values must be used with an awareness of how the filled data could impact the results of data analysis.