# Object Oriented Programming (OOP) - Fundamentals
Object-Oriented Programming (OOP) is a programming paradigm based on the concept of **objects**, which can contain **data** and **code**: data in the form of fields (often known as **attributes** or properties); and code in the form of procedures (often known as **methods**). This approach allows you to structure your software in a way that is extensible, maintainable, and intuitive, by encapsulating data and the operations on data in units called **classes** and **objects**. This encapsulation facilitates not just code organization and reuse but also the creation of complex data models that reflect real-world scenarios.

Key Concepts of OOP in Python:
 - **Classes**:
   - Definition: A class is a blueprint for creating objects. It defines a datatype by bundling data and functionalities together.
   - Example: Consider a class `Dog`. It represents the concept of a dog, not any specific dog.
 - **Objects**:
   - Definition: An object is an instance of a class. When class is defined, no memory is allocated until an object of that class is created.
   - Example: `my_dog = Dog()` creates an object `my_dog` of the class `Dog`.
 - **Attributes**:
   - Definition: Attributes are **data** stored inside a class or instance and represent the **state** or quality of the class or instance.
   - Types:
     - Instance Attributes: Unique to each instance (`my_dog.name = 'Buddy'`)
     - Class Attributes: Shared by all instances of a class (`Dog.species = 'Canis familiaris'`)
 - **Methods**:
   - Definition: Methods are **functions** defined inside a class. They are used to define the **behaviors** of an object.
   - Example: A method `bark()` in the `Dog` class might make a dog object ‘speak’.

## The `DataFrame` is an example of a class defined by pandas

In [1]:
from pandas import DataFrame

In [2]:
DataFrame

pandas.core.frame.DataFrame

In [3]:
type(DataFrame)

type

#### Individual instances (objects) of the DataFrame class can be created by invoking its constructor method
This can be invoked bare or with arguments.

In [4]:
df = DataFrame()

df

Empty DataFrame
Columns: []
Index: []

In [5]:
df = DataFrame(data=['a', 'b', 'c'], columns=['col1'])

df

  col1
0    a
1    b
2    c

In [6]:
type(df)

pandas.core.frame.DataFrame

#### All instances of the DataFrame class have attributes...

In [7]:
df.values

array([['a'],
       ['b'],
       ['c']], dtype=object)

In [8]:
df.shape

(3, 1)

#### ...and methods

In [9]:
df.sort_values(by='col1', ascending=False)

  col1
2    c
1    b
0    a

# Creating classes
New classes are defined with the `class` keyword, in a similar way to functions with `def`.

In [10]:
class Shape:
    pass

In [11]:
type(Shape)

type

In [12]:
sh = Shape()

In [13]:
type(sh)

__main__.Shape

New classes inherit some basic functionality from python's fundamental `object` class. We will come to **inheritance** later in the notebook, but what we need to understand for now is that when you create a class, it is automatically endowed with several methods inherited from python's `object` class. These are methods that allow python to interact with the object. e.g. when it is used as an argument of one of python's built-in functions or operators. These methods are known as **dunder** methods, bacause their names are wrapped with double underscores.

In [14]:
dir(sh)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__']

#### Setting class attributes
Class attributes in Python are variables defined at the class level. They are shared by all instances of the class.

In [15]:
class Shape:
    name = 'shape'

In [16]:
sh = Shape()

sh.name

'shape'

#### Setting instance attributes with `__init__()`
When the constructor method is invoked (by using parentheses after the name of the class), two things happen under the hood. Firstly, python calls the `__new__()` method of the class. This creates a new object with a location in memory (its `id`). Secondly, python passes this object to the `__init__()` or initialiser method of the class. This method can initialise the new object by setting additional **instance variables**.

The first argument to this `__init__()` method (the new object itself) is passed implicitly. It still requires a name however. This will act as a handle to refer to the object within its methods (including this one). This name can be anything but the strong convention is to use `self`. Any subsequent parameters defined in the signature of `__init__()` are used to initialise instance attributes.

In [17]:
class Shape:
    name = 'shape'
    def __init__(self, n_sides):
        self.n_sides = n_sides

In [18]:
# sh = Shape()

In [19]:
tri = Shape(3)

In [20]:
tri.name, tri.n_sides

('shape', 3)

#### Methods
Methods in Python are functions defined within a class that operate on the instances of the class. They are an essential part of object-oriented programming in Python, allowing objects to have **behaviors** in addition to attributes. Methods encapsulate behavior that is relevant to the class, and can interact with the class's attributes (state) and other methods, encapsulating functionality within the class.

In [21]:
class Shape:
    name = 'shape'
    def __init__(self, n_sides):
        self.n_sides = n_sides
        
    def print_sides(self):
        print(f'This {self.name} has {self.n_sides} sides.')

In [22]:
tri = Shape(3)

In [23]:
tri.print_sides()

This shape has 3 sides.

# Inheritance
Inheritance is a fundamental concept of object-oriented programming. It allows a new class to inherit attributes and methods from an existing class. This mechanism promotes code reuse and establishes a hierarchical relationship between classes.

When a class inherits from another class, it automatically takes on the attributes and methods of the parent class. This allows the child class to use and, optionally, override or extend the functionality of the parent class if it requires different functionality. Overriding methods of the parent class is done by defining a method with the same name in the child class. Extending functionality is ahchieved by adding new methods or attributes.

### Create a child class to represent a `Rectangle`
To create a child or derived class from a base class, we include the name of the base class in parentheses after declaring the name of the new class. If we don't add any further instructions, we will just have created a clone of the base class:

In [24]:
class Rectangle(Shape):
    pass

In [25]:
rect = Rectangle(6)

In [26]:
rect.print_sides()

This shape has 6 sides.

### In this case we want to modify the base class `Shape` to more specifically represent a rectangle
This can be achieved by:
 - overriding the parent class's `__init__()` method to initialise our `Rectangle` objects with relevant attributes, and to "hardcode" the `n_sides` attribute
 - overriding the `print_area()` method which was not implemented in `Shape`
 - extending the functionality of the parent class with a `scale()` method

In [27]:
class Rectangle(Shape):
    name = 'rectangle'
    def __init__(self, width, height):
        Shape.__init__(self, n_sides=4)
        self.width = width
        self.height = height
        
    def scale(self, width_factor, height_factor):
        self.width = self.width * width_factor
        self.height *= height_factor
        
    def print_area(self):
        area = self.width * self.height
        print(f'This {self.name} has area {area}.')

In [28]:
rect = Rectangle(5, 8)

In [29]:
rect.print_sides()

This rectangle has 4 sides.

In [30]:
rect.print_area()

This rectangle has area 40.

In [31]:
rect.scale(2, 1)

In [32]:
rect.width, rect.height

(10, 8)

In [33]:
rect.print_area()

This rectangle has area 80.

### More inheritance - the Square class
This example makes use of python's `super()` function. This is a built-in function that returns a proxy object. This object allows you to refer to the parent class (superclass) without naming it explicitly. It is most commonly used in class inheritance, particularly for accessing inherited methods from the parent class in a subclass. Using `super()` in the `__init__()` method ensures that the parent class is properly initialized. It also avoids the need to hardcode the parent class name, making the code more maintainable and adaptable to changes in the class hierarchy.

In the `Square` class example below, `super()` returns a proxy object of the `Rectangle` class. This example actually restricts the functionality of `Rectangle`, so that `Square` objects cannot be initialised or scaled to become non-square.

In [34]:
class Square(Rectangle):
    name = 'square'
    def __init__(self, side):
        super().__init__(width=side, height=side)
        
    def scale(self, factor):
        super().scale(width_factor=factor, height_factor=factor)

In [35]:
sq = Square(3)

In [36]:
sq.print_area()

This square has area 9.

In [37]:
sq.scale(3)

In [38]:
sq.print_area()

This square has area 81.

### The `@property` decorator
If we want the result of a method to be accessible as if it were an attribute of the object, we can use a **decorator** above the method declaration.

In [39]:
class Square(Rectangle):
    name = 'square'
    def __init__(self, side):
        super().__init__(width=side, height=side)
        
    def scale(self, factor):
        super().scale(width_factor=factor, height_factor=factor)
        
    @property
    def area(self):
        return self.width * self.height

In [40]:
sq = Square(5)

sq.area

25